version: "3.9"

volumes:
  mssql_data: {} # Persistent volume for MSSQL data
  kong_data: {} # Persistent volume for Kong database
  kong_prefix_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs
  kong_tmp_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs

networks:
  kong-net:
    external: false

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: cs261myPassword1234
      ACCEPT_EULA: Y
    networks:
      - kong-net
    volumes:
      - mssql_data:/var/opt/mssql # Persist database data
      - ./init-scripts:/docker-entrypoint-initdb.d # Mount initialization scripts

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - kong-net

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - mssql
    networks:
      - kong-net
