version: "3.9"

volumes:
    mssql_data: {} # Persistent volume for MSSQL data
    kong_data: {} # Persistent volume for Kong database
    kong_prefix_vol:
        driver_opts:
            type: tmpfs
            device: tmpfs
    kong_tmp_vol:
        driver_opts:
            type: tmpfs
            device: tmpfs

networks:
    kong-net:
        external: false

services:
    mssql:
        image: mcr.microsoft.com/mssql/server:2019-latest
        container_name: mssql
        ports:
            - "1433:1433"
        environment:
            SA_PASSWORD: cs261myPassword1234
            ACCEPT_EULA: Y
        networks:
            - kong-net
        volumes:
            - mssql_data:/var/opt/mssql # Persist database data
            - ./init-scripts:/docker-entrypoint-initdb.d # Mount initialization scripts

    frontend:
        build: ./frontend
        container_name: frontend
        ports:
            - "3000:3000"
        networks:
            - kong-net
        volumes:
            - ./frontend:/usr/app

    backend:
        build: ./backend
        container_name: backend
        ports:
            - "8080:8080"
        depends_on:
            - mssql
        networks:
            - kong-net

    kong-database:
        image: postgres:16.2
        container_name: kong-database
        environment:
            POSTGRES_DB: kong
            POSTGRES_USER: kong
            POSTGRES_PASSWORD: kong
        ports:
            - "5432:5432"
        networks:
            - kong-net
        volumes:
            - kong_data:/var/lib/postgresql/data

    kong-migrations:
        image: kong:3.6
        container_name: kong-migrations
        command: kong migrations bootstrap
        depends_on:
            - kong-database
        environment:
            KONG_PG_DATABASE: kong
            KONG_PG_HOST: kong-database
            KONG_PG_USER: kong
            KONG_PG_PASSWORD: kong
        networks:
            - kong-net

    kong:
        image: kong:3.6
        container_name: kong
        environment:
            KONG_PG_DATABASE: kong
            KONG_PG_HOST: kong-database
            KONG_PG_USER: kong
            KONG_PG_PASSWORD: kong
            KONG_ADMIN_ACCESS_LOG: /dev/stdout
            KONG_ADMIN_ERROR_LOG: /dev/stderr
            KONG_PROXY_LISTEN: 0.0.0.0:8000, 0.0.0.0:8443 ssl
            KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
            KONG_ADMIN_GUI_LISTEN: 0.0.0.0:8002
            KONG_PROXY_ACCESS_LOG: /dev/stdout
            KONG_PROXY_ERROR_LOG: /dev/stderr
            KONG_PREFIX: /var/run/kong
            KONG_DECLARATIVE_CONFIG: /opt/kong/kong.yaml
        ports:
            - "8000:8000"
            - "8443:8443"
            - "8001:8001"
            - "8444:8444"
            - "8002:8002"
        healthcheck:
            test: ["CMD", "kong", "health"]
            interval: 10s
            timeout: 10s
            retries: 10
        networks:
            - kong-net
        volumes:
            - kong_prefix_vol:/var/run/kong
            - kong_tmp_vol:/tmp
            - ./config:/opt/kong
