services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    command: npm start

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - mssql
    networks:
      - webnet

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql
    ports:
      - "1433:1433"
    env_file:
      - .env
    environment:
      SA_PASSWORD: ${SA_PASSWORD}
      ACCEPT_EULA: Y
    networks:
      - webnet

# network
networks:
  webnet: